elastic_apm:
  service_name: nlp-service
  secret_token: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  url: http://apm-server:8200

logstash:
  host: logstash
  port: 5000

rabbit:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest

celery:
  concurrency: 12

redis:
  host: redis
  port: 6379
  password: n3wsr3d1sp4ss
  db: 2