elastic_apm:
  service_name: nlp-service
  secret_token: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  host: localhost
  port: 8200

logstash:
  host: localhost
  port: 5000

rabbit:
  host: localhost
  port: 5672
  user: guest
  password: guest

celery:
  concurrency: 12

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 2