name: nlp-service-umbrella
description: NLP service umbrella helm chart
version: 0.0.0
appVersion: latest
apiVersion: v1
keywords:
  - nlp-service
sources:
home:
dependencies:
  - name: nlp-service
    version: 0.0.0
    repository: "file://../nlp-service"
  - name: redis
    version: 17.4.3
    repository: "https://charts.bitnami.com/bitnami"
  - name: rabbitmq
    version: 11.4.0
    repository: "https://charts.bitnami.com/bitnami"
  - name: monitor
    version: 1.0.2
    repository: "https://deejayrevok.github.io/helm-repo"
