apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nlp-celery-worker
  name: nlp-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nlp-celery-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nlp-celery-worker
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: nlp-service-configmap
        image: djrevok/nlp-celery-worker:latest
        imagePullPolicy: ""
        name: nlp-celery-worker
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
