name: NLP Services

on: [push]

jobs:

  nlp-service-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint and check score
        run: pylint-fail-under --fail_under 9  --ignore=Dockerfile,Dockerfile_celery,Dockerfile_flower,README.md,requirements.txt,requirements_celery.txt,requirements_flower.txt,nlp_celery_worker ./*
      - name: Test with unittest
        run: coverage run --source ./ --branch --omit=*__init__**,**tests**,**nlp_celery_worker** -m unittest discover -v ./tests/nlp_service
      - name: Check test coverage
        run: coverage report  --fail-under=80
      - name: Generate coverage report
        run: coverage xml -o coverage_nlp_service.xml
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage_nlp_service.xml
      - name: Free space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
      - name: Build the docker image
        run: docker build -t djrevok/nlp-service:latest .
      - name: Login to docker hub
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker@master
        with:
          args: push djrevok/nlp-service:latest

  nlp-celery-worker-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_celery.txt
      - name: Lint and check score
        run: pylint-fail-under --fail_under 9  --ignore=Dockerfile,Dockerfile_celery,Dockerfile_flower,README.md,requirements.txt,requirements_celery.txt,requirements_flower.txt,flower_app.py ./nlp_celery_worker/*
      - name: Test with unittest
        run: coverage run --source ./nlp_celery_worker --branch --omit=*__init__**,**tests**,**flower** -m unittest discover -v ./tests/nlp_celery_worker
      - name: Check test coverage
        run: coverage report  --fail-under=80
      - name: Generate coverage report
        run: coverage xml -o coverage_nlp_celery_worker.xml
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage_nlp_celery_worker.xml
      - name: Build the docker image
        run: docker build -t djrevok/nlp-celery-worker:latest -f Dockerfile_celery .
      - name: Login to docker hub
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker@master
        with:
          args: push djrevok/nlp-celery-worker:latest
