name: NLP Service CI

on:
  push:
    branches-ignore:
      - master

jobs:

  nlp-service-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint and check score
        run: pylint-fail-under --fail_under 9  --ignore=Dockerfile,README.md,requirements.txt,helm ./*
      - name: Test with unittest
        run: coverage run --source ./ --branch --omit=*__init__**,**tests**,**container_config.py**,helm -m unittest discover -v ./tests
      - name: Check test coverage
        run: coverage report  --fail-under=80
      - name: Generate coverage report
        run: coverage xml -o coverage_nlp_celery_worker.xml
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage_nlp_celery_worker.xml
      - name: Build the docker image
        run: docker build -t djrevok/nlp-celery-worker:latest .
      - name: Login to docker hub
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker@master
        with:
          args: push djrevok/nlp-celery-worker:latest
