name: NLP Service CI

on:
  push:
    branches-ignore:
      - master

jobs:

  nlp-service-CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: cp .env.example .env
    - name: Check formatting
      run: docker-compose run nlp-service tox -e black -- --check
    - name: Check style
      run: docker-compose run nlp-service tox -e flake8
    - name: Test with unittest
      run: docker-compose run nlp-service tox -e tests
    - name: Generate coverage report
      run: docker-compose run nlp-service tox -e coverage_report
    - name: Build the docker image
      run: docker build -t djrevok/nlp-service:latest .
    - name: Login to docker hub
      if: github.ref == 'refs/heads/develop'
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish docker image
      if: github.ref == 'refs/heads/develop'
      uses: actions-hub/docker@master
      with:
        args: push djrevok/nlp-service:latest
